# This is a basic workflow to help you get started with Actions

name: Update data

# Controls when the workflow will run
on:
  schedule:
    - cron: 0 12 * * 0

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: {}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: install cpanm and multiple modules
        uses: perl-actions/install-with-cpanm@v1
        with:
          install: Math::BigInt

      # Runs script
      - name: Get data
        run: |
          wget --no-verbose -O data/leeds/dm_premises.csv http://opendata.leeds.gov.uk/downloads/bins/dm_premises.csv
          wget --no-verbose -O data/leeds/dm_jobs.csv http://opendata.leeds.gov.uk/downloads/bins/dm_jobs.csv

      - name: Process bin data
        run: |
          perl processBinData.pl

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update data" || exit 0

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
